[package]
name = "rash-shell"
version = "0.2.0"
edition = "2018"
authors = ["Brandon Bremen <bbremen@gmail.com>"]
description = "A bourne-compatible shell inspired by dash"
license-file = "LICENSE"
exclude = [ "./.gitignore" ]
readme = "README.md"
repository = "https://github.com/absurdhero/rash-shell"

[build-dependencies]
lalrpop = { version = "0.19.1", features = ["lexer"] }

[dependencies]
log = "0.4.11"
pretty_env_logger = "0.4.0"
lalrpop-util = "0.19.1"
regex = "1.3.9"
nix = "0.18.0"
rustyline = "6.3.0"

[[bin]]
name = "rash"
path = "src/main.rs"
