[package]
name = "rash-shell"
version = "0.2.0"
edition = "2018"
authors = ["Brandon Bremen <bbremen@gmail.com>"]
categories = ["command-line-utilities"]
description = "A bourne-compatible shell inspired by dash"
exclude = [ "./.gitignore" ]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/absurdhero/rash-shell"

[build-dependencies]
lalrpop = { version = "0.19.5", features = ["lexer"] }

[dependencies]
log = "0.4.14"
pretty_env_logger = "0.4.0"
lalrpop-util = "0.19.5"
regex = "1.4.5"
nix = "0.20.0"
rustyline = "8.0.0"

[[bin]]
name = "rash"
path = "src/main.rs"
