[package]
name = "rash"
version = "0.1.0"
authors = ["Brandon Bremen <bbremen@gmail.com>"]

[build-dependencies]
lalrpop = "0.16.0"

[dependencies]
log = "*"
pretty_env_logger = "*"
lalrpop-util = "0.16.0"
regex = "1.0.5"
nix = "0.11.0"