[package]
name = "rash-shell"
version = "0.1.0"
edition = "2018"
authors = ["Brandon Bremen <bbremen@gmail.com>"]
description = "A bourne-compatible shell inspired by dash"
license-file = "LICENSE"
exclude = [ "./.gitignore" ]
readme = "README.md"
repository = "https://github.com/absurdhero/rash-shell"

[build-dependencies]
lalrpop = "0.16.1"

[dependencies]
log = "0.4.6"
pretty_env_logger = "0.2.5"
lalrpop-util = "0.16.1"
regex = "1.0.5"
nix = "0.11.0"
rustyline = "2.1.0"
void = "1.0.2"

[[bin]]
name = "rash"
path = "src/main.rs"
