[package]
name = "rash-shell"
version = "0.2.0"
edition = "2018"
authors = ["Brandon Bremen <bbremen@gmail.com>"]
description = "A bourne-compatible shell inspired by dash"
license-file = "LICENSE"
exclude = [ "./.gitignore" ]
readme = "README.md"
repository = "https://github.com/absurdhero/rash-shell"

[build-dependencies]
lalrpop = "0.17.2"

[dependencies]
log = "0.4.8"
pretty_env_logger = "0.3.1"
lalrpop-util = "0.17.2"
regex = "1.3.1"
nix = "0.16.0"
rustyline = "5.0.5"
void = "1.0.2"

[[bin]]
name = "rash"
path = "src/main.rs"
